env:
  es6: true
  node: true
  browser: true
  meteor: true
  mongo: true
  jquery: true
parser: babel-eslint
extends:
  - eslint:recommended
  - plugin:meteor/recommended
  - plugin:react/recommended
plugins:
  - meteor
  - react
rules:
  no-console: error
  meteor/template-names: off
  meteor/no-session: off
  indent:
    - error
    - 2
  max-len:
    - error
    - 80
    - 2
  object-curly-spacing:
    - error
    - always
  quotes:
    - error
    - single
  no-ternary: off
parserOptions:
  ecmaVersion: 2017
  sourceType: module
  ecmaFeatures:
    jsx: true
